---
# Install nginx
- name: Install packages
  community.general.zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: false
  loop:
    - nginx

# Copy nginx config
- name: Copy nginx config
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/conf.d/minio.conf"
    owner: root
    group: root
    mode: '0640'
  register: nginx_config_file

# Check nginx config
- name: Check nginx config
  command: nginx -t
  register: nginx_config_check
  changed_when: false

# Start nginx service
- name: Start nginx configuration
  service:
    name: nginx
    state: started
    enabled: true

# Start and enable nginx if config is ok
- name: Start and enable nginx
  systemd:
    name: nginx
    state: reloaded
  when: nginx_config_check.rc == 0 and nginx_config_file is changed

# Check nginx access
- name: Check nginx port access
  wait_for:
    host: "{{ keepalived_vip_address.split('/')[0] }}"
    port: 80
    state: started
    timeout: 5