kind: pipeline
type: kubernetes
name: minio-deploy

steps:
- name: terraform-deploy
  image: hashicorp/terraform:1.5.0
  commands:
  - terraform -chdir=./terraform init
  - terraform -chdir=./terraform plan
  - terraform -chdir=./terraform apply -auto-approve

- name: git-update
  image: plugins/git
  settings:
    depth: 1
    tags: true
    commit: true
    force: true
    branch: main
    repo: 
      from_secret: GIT_REPO
    username:
      from_secret: GIT_USERNAME
    password:
      from_secret: GIT_PASSWORD

#- name: ansible-deploy
#  image: ansible/ansible-runner:latest
#  commands:
#  - ansible-playbook -i ansible/inventory/hosts.ini ansible/install.yaml 