kind: pipeline
type: kubernetes
name: terraform

steps:
- name: check-syntax
  image: jmccann/drone-terraform:5
  settings:
    plan: false
  actions:
    - fmt
  fmt_options:
    write: false
    diff: true
    check: true
  tf_data_dir: terraform/

#- name: git-update
#  image: plugins/git
#  settings:
#    depth: 1
#    tags: true
#    commit: true
#    force: true
#    branch: main
#    repo: 
#      from_secret: GIT_REPO
#    username:
#      from_secret: GIT_USERNAME
#    password:
#      from_secret: GIT_PASSWORD

#- name: ansible-deploy
#  image: ansible/ansible-runner:latest
#  commands:
#  - ansible-playbook -i ansible/inventory/hosts.ini ansible/install.yaml 

volumes:
- name: ssh-config
  temp: {}