kind: pipeline
type: kubernetes
name: terraform

steps:
#- name: check-syntax
  #image: hashicorp/terraform:1.5.0
  #commands:
  #- ls -la terraform/
  #- terraform -chdir=./terraform fmt -check=true
  #- ls -la terraform/

- name: init
  image: hashicorp/terraform:1.5.0
  commands:
  - ls -la terraform/
  - terraform -chdir=./terraform init
  - ls -la terraform/
  volumes:
    - name: terraform
      path: /drone/src/terraform

- name: plan
  image: hashicorp/terraform:1.5.0
  commands:
  - terraform -chdir=./terraform plan
  volumes:
    - name: terraform
      path: /drone/src/terraform

#- name: git-update
#  image: plugins/git
#  settings:
#    depth: 1
#    tags: true
#    commit: true
#    force: true
#    branch: main
#    repo: 
#      from_secret: GIT_REPO
#    username:
#      from_secret: GIT_USERNAME
#    password:
#      from_secret: GIT_PASSWORD

#- name: ansible-deploy
#  image: ansible/ansible-runner:latest
#  commands:
#  - ansible-playbook -i ansible/inventory/hosts.ini ansible/install.yaml 

volumes:
- name: terraform
  temp: {}