- name: Minio node setup
  become: true
  hosts: all
  vars:
    filesystem_type: ext4
    swap_disk: /dev/vda
    minio_disk: /dev/vdb
    minio_disk_mount: /mnt/data
  tasks:
    ###############
    ## swap disk
    ###############
    - name: Check if swap disk is formatted
      ansible.builtin.command: blkid -s TYPE -o value "{{ swap_disk }}"
      register: fs_swap
      changed_when: false
      failed_when: false

    - name: Create a filesystem for swap
      community.general.filesystem:
        dev: "{{ swap_disk }}"
        fstype: swap
        force: true
      when: fs_swap.stdout is defined and (fs_swap.stdout != "swap" or not fs_swap.stdout)

    - name: Get swap disk UUID
      ansible.builtin.command: blkid -s UUID -o value {{ swap_disk }}
      register: uuid_swap
      changed_when: false

    ###############
    ## minio disk
    ###############
    - name: Check if minio disk is formatted
      ansible.builtin.command: blkid -s TYPE -o value "{{ minio_disk }}"
      register: fs_minio
      changed_when: false
      failed_when: false

    - name: Create a filesystem for minio
      community.general.filesystem:
        dev: "{{ minio_disk }}"
        fstype: "{{ filesystem_type }}"
        force: true
      when: fs_minio.stdout is defined and (fs_minio.stdout != filesystem_type or not fs_minio.stdout)

    - name: Get minio disk UUID
      ansible.builtin.command: blkid -s UUID -o value {{ minio_disk }}
      register: uuid_minio
      changed_when: false

    ###############
    ## mount created disks
    ###############
    - name: Add disks to fstab
      ansible.builtin.blockinfile:
        path: /etc/fstab
        state: present
        block: |
          UUID={{ uuid_swap.stdout }} swap swap defaults 0 0
          UUID={{ uuid_minio.stdout }} {{ minio_disk_mount }} {{ filesystem_type }} defaults 0 0
      when: uuid_swap.stdout is defined

    - name: Create directory for mounts
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: "0644"
      loop:
        - "{{ minio_disk_mount }}"

    - name: Enable swap
      ansible.builtin.command: swapon -a
      changed_when: false

    - name: Mount disks
      ansible.builtin.command: mount -a
      changed_when: false
