- name: Minio setup
  hosts: all
  remote_user: adamkoro
  become: true
  vars:
    filesystem_type: xfs
    swap_disk: /dev/vdb
    minio_disk: /dev/vdc
    minio_mount: /mnt/data
  tasks:
    ###############
    ## swap disk
    ###############
    - name: Check if swap disk is formatted
      ansible.builtin.command: blkid -s TYPE -o value "{{ swap_disk }}"
      register: fs_swap
      changed_when: false
      failed_when: false

    - name: Create a filesystem for swap
      community.general.filesystem:
        dev: "{{ swap_disk }}"
        fstype: swap
        force: false
      when: fs_swap.rc != 0 or fs_swap.stdout != "swap"

    - name: Get swap disk UUID
      ansible.builtin.command: blkid -s UUID -o value {{ swap_disk }}
      register: uuid_swap
      changed_when: false

    ###############
    ## datastore disk
    ###############
    - name: Check if datastore disk is formatted
      ansible.builtin.command: blkid -s TYPE -o value {{ minio_disk }}
      register: fs_minio
      changed_when: false
      failed_when: false

    - name: Format datastore disk
      community.general.filesystem:
        dev: "{{ minio_disk }}"
        fstype: "{{ filesystem_type }}"
        force: false
      when: fs_minio.rc != 0 or fs_minio.stdout != filesystem_type

    - name: Get datastore disk UUID
      ansible.builtin.command: blkid -s UUID -o value {{ minio_disk }}
      register: uuid_datastore
      changed_when: false


    ###############
    ## mount created disks
    ###############
    - name: Add disks to fstab
      ansible.builtin.blockinfile:
        path: /etc/fstab
        state: present
        block: |
          UUID={{ uuid_swap.stdout }} swap swap defaults 0 0
          UUID={{ uuid_datastore.stdout }} {{ minio_mount }} xfs defaults 0 0

    - name: Create directory for Minio data
      ansible.builtin.file:
        path: "{{ minio_mount }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Enable swap
      ansible.builtin.command: swapon -a
      changed_when: false

    - name: Mount disks
      ansible.builtin.shell: mount -a
      changed_when: false
