- name: Minio node setup
  become: true
  hosts: all
  vars:
    swap_disk: /dev/vda
    minio_disks:
      - { disk: "/dev/vdb", filesystem_type: "xfs", mount: "/mnt/minio1" }
      - { disk: "/dev/vdc", filesystem_type: "xfs", mount: "/mnt/minio2" }
      - { disk: "/dev/vdd", filesystem_type: "xfs", mount: "/mnt/minio3" }
      - { disk: "/dev/vde", filesystem_type: "xfs", mount: "/mnt/minio4" }
      - { disk: "/dev/vdf", filesystem_type: "xfs", mount: "/mnt/minio5" }
      - { disk: "/dev/vdg", filesystem_type: "xfs", mount: "/mnt/minio6" }
  tasks:
    ###############
    ## swap disk
    ###############
    - name: Check if swap disk is formatted
      ansible.builtin.command: blkid -s TYPE -o value "{{ swap_disk }}"
      register: fs_swap
      changed_when: false
      failed_when: false

    - name: Create a filesystem for swap
      community.general.filesystem:
        dev: "{{ swap_disk }}"
        fstype: swap
        force: true
      when: fs_swap.stdout is defined and (fs_swap.stdout != "swap" or not fs_swap.stdout)

    - name: Get swap disk UUID
      ansible.builtin.command: blkid -s UUID -o value {{ swap_disk }}
      register: uuid_swap
      changed_when: false

    - name: Add disks to fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        state: present
        line: UUID={{ uuid_swap.stdout }} swap swap defaults 0 0
      when: uuid_swap.stdout is defined

    ###############
    ## minio disk
    ###############
    - name: Check if minio disk is formatted
      ansible.builtin.command: blkid -s TYPE -o value "{{ item.disk }}"
      register: fs_minio
      changed_when: false
      failed_when: false
      loop: "{{ minio_disks }}"
      loop_control:
        loop_var: item

    - name: Create a filesystem for minio
      community.general.filesystem:
        dev: "{{ item.disk }}"
        fstype: "{{ item.filesystem_type }}"
        force: true
      when: fs_minio.results[item_index].stdout is defined and(fs_minio.results[item_index].stdout != item.filesystem_type or not fs_minio.results[item_index].stdout)
      loop: "{{ minio_disks }}"
      loop_control:
        loop_var: item
        index_var: item_index

    - name: Get minio disk UUID
      ansible.builtin.command: blkid -s UUID -o value {{ item.disk }}
      register: uuid_minio
      changed_when: false
      loop: "{{ minio_disks }}"
      loop_control:
        loop_var: item

    - name: Add disks to fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        state: present
        line: UUID={{ uuid_minio.results[item_index].stdout }} {{ item.mount }} {{ item.filesystem_type }} defaults 0 0
      when: uuid_minio.results[item_index].stdout is defined
      loop: "{{ minio_disks }}"
      loop_control:
        loop_var: item
        index_var: item_index

    - name: Create directory for mounts
      ansible.builtin.file:
        path: "{{ item.mount }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      loop: "{{ minio_disks }}"
      loop_control:
        loop_var: item

    - name: Enable swap
      ansible.builtin.command: swapon -a
      changed_when: false

    - name: Mount disks
      ansible.builtin.command: mount -a
      changed_when: false
