---
# Create Minio group
- name: Create Minio group
  group:
    name: minio-user

# Create Minio user
- name: Create Minio user
  user:
    name: minio-user
    groups:
      - minio-user

# Owner of Minio data
- name: Change owner of Minio data
  file:
    path: "{{ minio_data_path }}"
    owner: minio-user
    group: minio-user
    mode: '0750'
    recurse: true

# Get Minio binary
- name: Download Minio binary
  get_url:
    url: "{{ minio_download_url }}/{{ minio_binary_file }}"
    dest: /usr/local/bin/minio
    owner: root
    group: root
    mode: '0755'
    validate_certs: true
  register: minio_binary_file

# Copy Minio config
- name: Copy Minio config
  template:
    src: "minio.config.j2"
    dest: "/etc/default/minio"
    owner: minio-user
    group: minio-user
    mode: '0700'
  register: minio_config_file

# Copy Minio service
- name: Copy Minio service
  template:
    src: "minio.service.j2"
    dest: "/etc/systemd/system/minio.service"
    owner: root
    group: root
    mode: '0755'
  register: minio_service_file

# Start and enable Minio
- name: Start and enable Minio
  systemd:
    name: minio
    daemon_reload: true
    state: started
    enabled: true

# Restart Minio
- name: Start and enable Minio
  systemd:
    name: minio
    state: restarted
  when:
    - minio_binary_file is changed or minio_config_file is changed or minio_service_file is changed
