---
- name: Gather facts
  hosts: all
  gather_facts: true

- name: Setup loadbalancer cluster
  hosts: loadbalancer
  become: true
  roles:
    - role: loadbalancer

- hosts: Setup minio cluster
  become: true
  roles:
    - role: minio
