- name: Install packages
  community.general.zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: false
  loop:
    - nginx

- name: Copy nginx config
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/conf.d/minio.conf"
    owner: root
    group: root
    mode: '0644'

- name: Check nginx config
  command: nginx -t
  register: nginx_config_check
  changed_when: false

- name: Start and enable nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: nginx_config_check.rc == 0

